/**
 * shared/types/capability.ts -- the capability tiers and the gate's own
 * approval-lifecycle types. Split out of shared/types.ts, 2026-08-12.
 */

// ---------------------------------------------------------------------------
// Capabilities and the gate
// ---------------------------------------------------------------------------

export type Capability =
  // green — automatic, still logged
  | "MEMORY_READ"
  | "FS_READ"
  | "CAMERA"
  | "NET_READ"
  // Opening/closing an app, project, or website -- owner request,
  // 2026-08-07: low-risk, immediately visible (a window opens/closes),
  // trivially reversible, and the repeated approval-per-open was pure
  // friction with no real safety benefit. Deliberately narrower than
  // all of SHELL_EXEC: media control, volume/brightness, clipboard
  // write, and screenshot stay SHELL_EXEC/yellow -- not part of this
  // request, different risk profile (clipboard/screenshot can expose
  // sensitive content; this tier is reserved for "opens/closes a
  // window," nothing that reads or captures anything).
  | "APP_CONTROL"
  // Reading/writing the owner's real Reminders.app tasks -- owner
  // request, 2026-08-12: same reasoning as APP_CONTROL above (narrow,
  // immediately visible in Reminders.app itself, trivially reversible
  // by deleting/unchecking an item), presented and explicitly chosen
  // over the SHELL_EXEC/yellow default that a system-app write would
  // otherwise get, because per-call approval on every "add a task"
  // would undo this same SOAK's own approval-fatigue fix. Scoped to
  // exactly one executor's CRUD (`core/executors/reminders.ts`) --
  // not a precedent for widening SHELL_EXEC, same explicit boundary
  // APP_CONTROL's own entry draws.
  | "REMINDERS"
  // Real macOS cursor movement + clicks, hand-driven -- owner request,
  // 2026-08-12. A broader "click anywhere, no confirmation" version was
  // proposed first and explicitly refused (see DECISIONS.md's ADR):
  // a click that can land anywhere has no way to know whether it's
  // hitting a harmless link or a "Send"/"Delete"/payment-confirm
  // button, so it has to be judged at the worst case it could reach --
  // which is red-tier territory. This capability is green anyway,
  // because it isn't the same shape as the rest of the green tier: cursor
  // *movement* is the harmless, auto-run part (visible, trivially
  // undone), but the actual *click* never fires from a gesture, a
  // model, or a voice command alone -- only a real, physical keypress
  // fires it (`senses/eyes/pointer.py`'s `ClickTrigger`), reusing
  // CLAUDE.md § 5's own red-tier pattern ("a real keystroke fires it")
  // as a structural property of the executor itself rather than
  // routing every individual click through the approval queue, which
  // would be absurd for something as routine as a mouse click and would
  // defeat hands-free pointing entirely.
  | "POINTER_CONTROL"
  // yellow — requires approval
  | "MEMORY_WRITE"
  | "FS_WRITE"
  | "GIT_WRITE"
  | "SHELL_EXEC"
  | "WEBHOOK"
  // Every MCP tool call, uniformly -- deliberately not tiered per-tool
  // by trusting a server's own self-declared `readOnlyHint`/
  // `destructiveHint` annotations (real MCP security research, 2026-08-05
  // capability research in docs/BACKLOG.md: those hints are the
  // *server's* own claim, not independently verified, and CLAUDE.md § 0.5's
  // "trust never comes from a model/external claim" reasoning applies
  // here too). A future per-tool tier is a real design question, not
  // assumed safe by default.
  | "MCP_TOOL_CALL";
// red capabilities are deliberately absent from this union. They are not
// reachable by any code path. Adding one here is a security decision.

export const GREEN_CAPABILITIES: readonly Capability[] = [
  "MEMORY_READ",
  "FS_READ",
  "CAMERA",
  "NET_READ",
  "APP_CONTROL",
  "REMINDERS",
  "POINTER_CONTROL",
] as const;

export type ApprovalState =
  | "pending"
  | "approved"
  | "rejected"
  | "expired"
  | "executed";

export interface ApprovalRequest {
  id: string; // ulid
  /** Single use. Spending it twice fails closed and logs a replay event. */
  nonce: string;
  createdAt: number;
  expiresAt: number;
  capability: Capability;
  skillId: string;
  /**
   * What the owner reads before deciding. Generated by the `converse` lane.
   * A misleading summary is a security hole — this text is the security
   * boundary, not the payload.
   */
  humanSummary: string;
  /** The full thing, shown on expand. */
  payload: unknown;
  /** Rendered as a diff in the dashboard when present. */
  diff?: string;
  state: ApprovalState;
}

export interface ApprovalResponse {
  requestId: string;
  nonce: string;
  decision: "approve" | "reject";
  decidedAt: number;
  /** How the decision arrived -- forensic value the audit log didn't
   * have before (`docs/BACKLOG.md`'s "tag the audit log with which
   * channel resolved an approval" idea, built 2026-08-11): it recorded
   * *that* a decision happened, never *how*. `"voice"` doesn't exist
   * yet (CLAUDE.md § 5's own rule: a red-tier send still needs a real
   * click/keystroke, never a spoken "yes" alone) -- reserved so the enum
   * doesn't need revisiting when it does. Optional: a client that
   * doesn't set it (or an older one) just logs an audit entry with no
   * channel, not an error. */
  channel?: "dashboard" | "cli" | "voice";
}

export type ApprovalOutcome =
  | { ok: true; result: unknown }
  | { ok: false; reason: "rejected" | "expired" | "replay" | "error"; detail?: string };

/** A skill produces these. It never produces an action. */
export interface ProposedAction {
  capability: Capability;
  humanSummary: string;
  payload: unknown;
  diff?: string;
  /** Overrides the 5-minute default. */
  expiresInMs?: number;
}

/** Signed envelope handed to an executor. Executors verify before acting. */
export interface SignedExecution {
  requestId: string;
  nonce: string;
  payload: unknown;
  issuedAt: number;
  /** HMAC-SHA256 over {requestId, nonce, payload, issuedAt}. */
  signature: string;
}
