/**
 * shared/types.ts — the contract.
 *
 * Single source of truth for every boundary in the system: core <-> ui,
 * core <-> senses, core <-> skills. Python models are generated from the JSON
 * Schema derived from this file (`make types`). Do not define these shapes
 * anywhere else.
 */

// ---------------------------------------------------------------------------
// Router
// ---------------------------------------------------------------------------

export type Lane = "reflex" | "converse" | "reason" | "see" | "act";

export type CostTier = "free-local" | "free-remote" | "paid";

export interface ChatRequest {
  lane: Lane;
  system: string;
  messages: ChatMessage[];
  /** Ask the provider for strict JSON. Providers that cannot must reject. */
  jsonSchema?: object;
  maxTokens?: number;
  temperature?: number;
  /** Hard deadline. The router aborts and falls through on expiry. */
  timeoutMs: number;
}

export interface ChatMessage {
  role: "system" | "user" | "assistant";
  content: string;
}

export interface ChatChunk {
  delta: string;
  done: boolean;
}

export interface VisionRequest {
  imagePath: string;
  prompt: string;
  /** When set, the provider must return JSON matching this shape. */
  jsonSchema?: object;
  timeoutMs: number;
}

export interface VisionResult {
  /** What was seen, in words. This is the durable record. Always present. */
  qualitative: string;
  /** Optional structured extraction. May be null if the model was unsure. */
  structured: object | null;
  /** Honest self-assessment, 0..1. Providers that cannot produce this return 0.5. */
  confidence: number;
}

/** Emitted for every router call. This is how we learn what to change. */
export interface RouterTrace {
  requestId: string;
  lane: Lane;
  providerId: string;
  costTier: CostTier;
  latencyMs: number;
  /** 0 = first choice served it. >0 = fallbacks were used. */
  fallbackDepth: number;
  ok: boolean;
  error?: string;
}

// ---------------------------------------------------------------------------
// Capabilities and the gate
// ---------------------------------------------------------------------------

export type Capability =
  // green — automatic, still logged
  | "MEMORY_READ"
  | "FS_READ"
  | "CAMERA"
  | "NET_READ"
  // Opening/closing an app, project, or website -- owner request,
  // 2026-08-07: low-risk, immediately visible (a window opens/closes),
  // trivially reversible, and the repeated approval-per-open was pure
  // friction with no real safety benefit. Deliberately narrower than
  // all of SHELL_EXEC: media control, volume/brightness, clipboard
  // write, and screenshot stay SHELL_EXEC/yellow -- not part of this
  // request, different risk profile (clipboard/screenshot can expose
  // sensitive content; this tier is reserved for "opens/closes a
  // window," nothing that reads or captures anything).
  | "APP_CONTROL"
  // Reading/writing the owner's real Reminders.app tasks -- owner
  // request, 2026-08-12: same reasoning as APP_CONTROL above (narrow,
  // immediately visible in Reminders.app itself, trivially reversible
  // by deleting/unchecking an item), presented and explicitly chosen
  // over the SHELL_EXEC/yellow default that a system-app write would
  // otherwise get, because per-call approval on every "add a task"
  // would undo this same SOAK's own approval-fatigue fix. Scoped to
  // exactly one executor's CRUD (`core/executors/reminders.ts`) --
  // not a precedent for widening SHELL_EXEC, same explicit boundary
  // APP_CONTROL's own entry draws.
  | "REMINDERS"
  // yellow — requires approval
  | "MEMORY_WRITE"
  | "FS_WRITE"
  | "GIT_WRITE"
  | "SHELL_EXEC"
  | "WEBHOOK"
  // Every MCP tool call, uniformly -- deliberately not tiered per-tool
  // by trusting a server's own self-declared `readOnlyHint`/
  // `destructiveHint` annotations (real MCP security research, 2026-08-05
  // capability research in docs/BACKLOG.md: those hints are the
  // *server's* own claim, not independently verified, and CLAUDE.md § 0.5's
  // "trust never comes from a model/external claim" reasoning applies
  // here too). A future per-tool tier is a real design question, not
  // assumed safe by default.
  | "MCP_TOOL_CALL";
// red capabilities are deliberately absent from this union. They are not
// reachable by any code path. Adding one here is a security decision.

export const GREEN_CAPABILITIES: readonly Capability[] = [
  "MEMORY_READ",
  "FS_READ",
  "CAMERA",
  "NET_READ",
  "APP_CONTROL",
  "REMINDERS",
] as const;

export type ApprovalState =
  | "pending"
  | "approved"
  | "rejected"
  | "expired"
  | "executed";

export interface ApprovalRequest {
  id: string; // ulid
  /** Single use. Spending it twice fails closed and logs a replay event. */
  nonce: string;
  createdAt: number;
  expiresAt: number;
  capability: Capability;
  skillId: string;
  /**
   * What the owner reads before deciding. Generated by the `converse` lane.
   * A misleading summary is a security hole — this text is the security
   * boundary, not the payload.
   */
  humanSummary: string;
  /** The full thing, shown on expand. */
  payload: unknown;
  /** Rendered as a diff in the dashboard when present. */
  diff?: string;
  state: ApprovalState;
}

export interface ApprovalResponse {
  requestId: string;
  nonce: string;
  decision: "approve" | "reject";
  decidedAt: number;
  /** How the decision arrived -- forensic value the audit log didn't
   * have before (`docs/BACKLOG.md`'s "tag the audit log with which
   * channel resolved an approval" idea, built 2026-08-11): it recorded
   * *that* a decision happened, never *how*. `"voice"` doesn't exist
   * yet (CLAUDE.md § 5's own rule: a red-tier send still needs a real
   * click/keystroke, never a spoken "yes" alone) -- reserved so the enum
   * doesn't need revisiting when it does. Optional: a client that
   * doesn't set it (or an older one) just logs an audit entry with no
   * channel, not an error. */
  channel?: "dashboard" | "cli" | "voice";
}

export type ApprovalOutcome =
  | { ok: true; result: unknown }
  | { ok: false; reason: "rejected" | "expired" | "replay" | "error"; detail?: string };

/** A skill produces these. It never produces an action. */
export interface ProposedAction {
  capability: Capability;
  humanSummary: string;
  payload: unknown;
  diff?: string;
  /** Overrides the 5-minute default. */
  expiresInMs?: number;
}

/** Signed envelope handed to an executor. Executors verify before acting. */
export interface SignedExecution {
  requestId: string;
  nonce: string;
  payload: unknown;
  issuedAt: number;
  /** HMAC-SHA256 over {requestId, nonce, payload, issuedAt}. */
  signature: string;
}

// ---------------------------------------------------------------------------
// Memory
// ---------------------------------------------------------------------------

export type EventKind =
  | "utterance"    // the owner spoke
  | "response"     // jarvis spoke
  | "observation"  // the camera saw
  | "action"       // something was executed
  | "approval"
  | "rejection"
  | "note";        // system or manual

export interface MemoryEvent {
  id: string;
  ts: number;
  kind: EventKind;
  actor: "owner" | "jarvis" | "system";
  content: string;
  meta?: Record<string, unknown>;
  sessionId?: string;
}

export interface Fact {
  id: string;
  /** Dotted namespace, e.g. "diet.avoids", "project.hoqueimanager.stack". */
  key: string;
  value: string;
  /** Honest. Do not round up to look confident. */
  confidence: number;
  sourceEventId?: string;
  updatedAt: number;
}

export interface Observation {
  id: string;
  ts: number;
  /** Local path. Never leaves the machine unless the `see` lane fell through
   *  to a remote provider, which is logged. */
  imagePath: string;
  provider: string;
  qualitative: string;
  structured: object | null;
  confidence: number;
}

// ---------------------------------------------------------------------------
// Estimates — see SPEC.md § 7 and ADR-011
// ---------------------------------------------------------------------------

/**
 * A number the system inferred rather than measured.
 *
 * There is deliberately no `value` field. Code that wants a single number from
 * an estimate has to make that choice explicitly and visibly, and review will
 * catch it. Never sum these.
 *
 * NOTE: this type must never appear in the nutrition or workbench paths. There,
 * quantities are always `Measurement` with source `declared`. `Estimate` exists
 * for genuinely uncertain things — a vision identification's confidence, a
 * coach's inferred pattern strength. See ADR-011.
 */
export interface Estimate {
  low: number;
  high: number;
  unit: string;
  confidence: number;
  source: "vision" | "inferred";
}

/**
 * A number the owner declared, or that came from a scale, label or database.
 * Safe to sum. This is the only kind of number that gets stored as fact.
 */
export interface Measurement {
  value: number;
  unit: string;
  /** `declared` = the owner said it out loud and confirmed the read-back. */
  source: "declared" | "scale" | "barcode";
}

export type Quantity = Estimate | Measurement;

export function isMeasured(q: Quantity): q is Measurement {
  return "value" in q;
}

// ---------------------------------------------------------------------------
// Skills
// ---------------------------------------------------------------------------

export interface SkillInput {
  utterance: string;
  intent: string;
  sessionId: string;
  /** Populated only when the intent requires an image. */
  imagePath?: string;
}

export interface SkillResult {
  /** Spoken to the owner. Streamed sentence by sentence. */
  speech: string;
  /** Optional richer payload for the dashboard. */
  display?: unknown;
  /** Events the skill wants written. Subject to MEMORY_WRITE approval. */
  remember?: Omit<MemoryEvent, "id" | "ts">[];
}

// ---------------------------------------------------------------------------
// Live channel: core -> ui
// ---------------------------------------------------------------------------

/** What JARVIS is doing right now, independent of `speaking` -- so the
 * owner can watch a request actually move (listening -> thinking ->
 * speaking) instead of taking "it's working on it" on faith. Each value
 * traces to a real signal, not a guess: `listening` from `senses/ears`
 * arming the mic, `thinking` from an utterance landing in `core`'s
 * dispatch loop, back to `idle` once that turn is fully handled. */
export type JarvisState = "idle" | "listening" | "thinking";

export type FeedbackRating = "up" | "down";

export type ServerEvent =
  | { type: "thought"; text: string; lane: Lane; ts: number }
  | { type: "trace"; trace: RouterTrace }
  | { type: "approval.new"; request: ApprovalRequest }
  | { type: "approval.resolved"; requestId: string; state: ApprovalState }
  /** `eventId` is absent for the owner's own line (nothing to rate) and
   * present for `jarvis` lines backed by a real `events` row, so the
   * dashboard can attach a thumbs up/down without a second round trip. */
  | { type: "transcript"; text: string; final: boolean; speaker: "owner" | "jarvis"; eventId?: string }
  | { type: "state"; value: JarvisState }
  | { type: "speaking"; active: boolean }
  /** Folded in from `CameraEvent` (below) -- the dashboard needs the same
   * real detail (expiry, close cause) `core` gets from `eyes`, not just
   * an on/off boolean. */
  | { type: "camera.armed"; sessionId: string; reason: string; expiresAt: number }
  | { type: "camera.captured"; sessionId: string; frameId: string; path: string }
  | { type: "camera.closed"; sessionId: string; cause: "owner" | "idle" | "cap" | "error" }
  /** Continuous hand tracking (2026-08-12, `senses/eyes/gestures.py`).
   * A distinct mode from the camera's single-shot `capture()`, not a
   * loosening of SPEC.md § 6: frames are analyzed in memory by a local
   * model and dropped -- nothing written to disk, nothing sent to a
   * remote model. Landmarks are normalized 0..1, already mirrored to
   * match the preview image so the overlay lines up. */
  | { type: "gesture.started" }
  | { type: "gesture.stopped"; cause: "owner" | "idle" | "error" }
  | { type: "hand.landmarks"; hands: HandLandmarks[]; ts: number }
  /** Base64 JPEG, deliberately rate-limited below the landmark rate --
   * the skeleton overlay is drawn browser-side from the landmarks above,
   * so only this (the expensive part) is throttled. */
  | { type: "hand.preview"; image: string }
  /** Live microphone level, 0..1, log-scaled (`senses/ears/audio_level.py`).
   * Throttled to ~10/s at the source -- decorative, and nobody perceives
   * a level meter faster than that. */
  | { type: "audio.level"; level: number }
  | { type: "health"; providers: Record<string, boolean> }
  /** `ears`/`voice`/`eyes` connection state, per sense -- distinct from
   * `health` (LLM router providers, above). Found live, 2026-08-07: a
   * dropped sense connection had no dashboard-visible signal at all,
   * only a real bug in `core/main.ts`'s reconnect handling (fixed the
   * same day, `core/senseConnection.ts`) made this observable in the
   * first place -- see PROGRESS.md's dated entry. */
  | { type: "sense.connection"; sense: "ears" | "voice" | "eyes"; connected: boolean }
  /** A turn failed. Spoken to the owner too (persona.md) -- this is the
   * dashboard-visible half of the same honesty rule, not a replacement
   * for it. `detail` is a plain message, never a raw stack trace. */
  | { type: "error"; message: string; detail?: string; ts: number }
  /** Relayed to every tab after a rating lands, same "two tabs stay in
   * sync" reasoning as approvals -- state lives in `core`, not the tab
   * that clicked. */
  | { type: "feedback"; eventId: string; rating: FeedbackRating };

export type ClientEvent =
  | { type: "approval.decide"; response: ApprovalResponse }
  | { type: "mute"; category: string; muted: boolean }
  /** Dashboard "test console" (SOAK 1): feeds a typed line into the exact
   * same handling path a real transcribed utterance goes through --
   * `core` cannot tell the difference, which is the point: real usage
   * data without needing a working mic every time. */
  | { type: "utterance.inject"; text: string }
  /** Rates a `jarvis` response, owner-only judgement (CLAUDE.md § 0.5:
   * never model-generated). Purely diagnostic -- never gated, never fed
   * back into `Memory.recall()`. */
  | { type: "feedback"; eventId: string; rating: FeedbackRating }
  /** Toggles background blur on the gesture-mode preview only -- landmark
   * detection always runs on the real, unblurred frame
   * (`senses/eyes/gestures.py`). A no-op if gesture tracking isn't
   * currently running. Sent directly, not through a skill/capability:
   * purely cosmetic, no side effect beyond what the owner already made
   * visible by turning hand tracking on. */
  | { type: "gesture.blur"; enabled: boolean };

// ---------------------------------------------------------------------------
// Camera — see SPEC.md § 6 and ADR-010
// ---------------------------------------------------------------------------

/**
 * ARMED does not mean recording. Arming the camera captures nothing; a frame
 * is taken only when a request is made.
 */
export type CameraState = "idle" | "armed" | "capturing" | "analysing";

export interface CameraSession {
  readonly id: string;
  readonly openedAt: number;
  /** Absolute cap. Default 10 minutes. */
  readonly expiresAt: number;
  /** Rolling idle deadline. Default 120s, reset on each capture. */
  readonly idleUntil: number;
  readonly reason: string;

  /** Grabs a fresh frame. Follow-ups never reuse the previous one. */
  capture(): Promise<Frame>;
  /** Deletes every frame not referenced by an approved observation. */
  close(): Promise<void>;
  /** Starts/stops continuous hand tracking on this session's own device
   * (`senses/eyes/gestures.py`). Fire-and-forget on purpose: the result
   * is a continuous `hand.landmarks` stream to the dashboard, not a
   * single reply worth awaiting here. Stopping is idempotent, and
   * `close()` stops tracking too -- tracking can never outlive the
   * session that owns the camera. */
  startGestures(): void;
  stopGestures(): void;
}

export interface CameraHandle {
  /** Throws if the calling skill did not declare CAMERA in its manifest. */
  open(reason: string): Promise<CameraSession>;
  readonly state: CameraState;
}

export interface Frame {
  path: string;       // data/frames/<sessionId>/<ulid>.jpg — local only
  capturedAt: number;
  sessionId: string;
  /** True once an approved observation references it; survives session close. */
  retained: boolean;
}

/** One detected hand: MediaPipe's own 21-point topology, normalized
 * 0..1. Index 4 is the thumb tip and index 8 the index-finger tip (the
 * two the dashboard's pinch detection uses) -- that ordering is
 * MediaPipe's fixed, documented convention, not something this project
 * chose. `handedness` is the model's own "Left"/"Right" label. */
export interface HandLandmarks {
  handedness: string;
  landmarks: { x: number; y: number; z: number }[];
}

export type CameraEvent =
  | { type: "camera.armed"; sessionId: string; reason: string; expiresAt: number }
  | { type: "camera.captured"; sessionId: string; frameId: string; path: string }
  | { type: "camera.closed"; sessionId: string; cause: "owner" | "idle" | "cap" | "error" };

// ---------------------------------------------------------------------------
// Skills — see docs/SKILLS.md
// ---------------------------------------------------------------------------

export interface SkillIntent {
  id: string;
  description: string;
  /**
   * Embedded at load time and used for routing. Not documentation.
   * Write them the way you actually speak, including terse and sloppy forms.
   * Five to eight per intent.
   */
  examples: string[];
  lanes: Lane[];
  requiresCamera?: boolean;
}

export interface SkillManifest {
  id: string;
  version: string;
  description: string;
  intents: SkillIntent[];
  capabilities: Capability[];
  /** Labels the skill in the dashboard and tightens gate defaults. */
  sensitivity?: "normal" | "personal";
}

export type SkillStatus = "loaded" | "disabled";

export interface SkillHealth {
  id: string;
  version: string;
  status: SkillStatus;
  lastError?: string;
  loadedAt?: number;
}

/** Logged for every dispatch. When the wrong skill fires, this says why. */
export interface SkillRoutingTrace {
  utterance: string;
  lane: Lane;
  candidates: { skillId: string; intentId: string; score: number }[];
  chosen?: { skillId: string; intentId: string };
  /** True when the embedding match was ambiguous and a model broke the tie. */
  disambiguated: boolean;
}

// ---------------------------------------------------------------------------
// Nutrition — quantities are declared, never estimated. ADR-011.
// ---------------------------------------------------------------------------

export interface FoodItem {
  name: string;
  /** Absent when the owner did not give one. Never filled in by a model. */
  quantity?: Measurement;
  /** Only present when the lookup table had a hit for this food and quantity. */
  nutrition?: {
    kcal: number;
    proteinG: number;
    carbsG: number;
    fatG: number;
    source: "openfoodfacts" | "usda";
  };
  /** Set when vision proposed the name and the owner accepted or corrected it. */
  identifiedBy?: "owner" | "vision-confirmed" | "vision-corrected";
}

export interface MealLog {
  id: string;
  at: number;
  items: FoodItem[];
  /** Frame retained only if the owner approved keeping it. */
  framePath?: string;
  confirmedAt: number;
}

// ---------------------------------------------------------------------------
// Dashboard live-data panels (SOAK 1) — read/write views onto a skill's own
// `ctx.store` table, built for the two list-shaped skills that have one
// (`tasks`, `shopping_list`). Deliberately not a generic "any skill's
// store" API: only two skills have this shape today, and guessing a
// generic shape for hypothetical future ones is exactly the kind of
// premature abstraction CLAUDE.md § 0.6 warns against.
// ---------------------------------------------------------------------------

export interface TaskItem {
  id: string;
  text: string;
  done: boolean;
  createdAt: number;
}

export interface ShoppingItem {
  id: string;
  text: string;
  createdAt: number;
}

// ---------------------------------------------------------------------------
// Dashboard metrics (SOAK 1) — aggregated from `routing_stats` (one row per
// dispatch decision) and `events`, so the dashboard can show whether real
// usage is actually working, not just individual turns. See
// `core/metrics.ts`'s own docstring for why this is a pure, separately
// testable function over raw rows rather than SQL aggregation.
// ---------------------------------------------------------------------------

export interface SkillHitRate {
  skillId: string;
  intentId: string;
  count: number;
}

export interface DashboardMetrics {
  utterancesToday: number;
  utterancesThisWeek: number;
  laneDistribution: Partial<Record<Lane, number>>;
  skillHitRate: SkillHitRate[];
  noSkillMatchedCount: number;
  /** 0..1 of all routing decisions in the window, not just today's. */
  noSkillMatchedRate: number;
  totalRoutingDecisions: number;
}
